### ISSUE TITLE
What about security, languages and changes marketing plan?

### ISSUE THREAD

**Issue by uaway** [santosh3700/MLM-Website-Using-PHP-Binary-Plan-Version-2.0-Final#1]
Hi, 
Thank you for your great job! 
I found a link to this project on Quora.com and want to ask some questions before install it.

1) What about **security** of php files and core? Must I be warry about it and must check files?

2) I want to use other then English **language** but I can`t find any language files in package, I must change all files?

3) Can I change **marketing plan** form Binary to 3x3? What I must change? Can I do it into admin panel?

**Comment by santosh3700** [comment]
> Hi,
> Thank you for your great job!
> I found a link to this project on Quora.com and want to ask some questions before install it.
> 
> 1. What about **security** of php files and core? Must I be warry about it and must check files?
> 2. I want to use other then English **language** but I can`t find any language files in package, I must change all files?
> 3. Can I change **marketing plan** form Binary to 3x3? What I must change? Can I do it into admin panel?

Hi Uaway,,
this project was for tutorial purposes. Students or developers who wanted to know how they can build a MLM Website using PHP, they can learn from here.

Actually I will not recommend this project for production purposes. Because there are no security features implemented yet. And this project needs much work to move it to production.
